### PR TITLE
Feature/syntactic extension for variables

### PR DESCRIPTION
**Pull request by grrim**
Add syntactic extension for (self)variables, (self)switches, using proxies : 

- `S[id]` returns the switch (by his **id**)

- `V[id]` returns the variable (by his **id**)

- `S[id] = new_value` set a new value for a switch

- `V[id] = new_value` set a new value for a variable 

- `SS[id]` get the selfSwitch for the current event  (**ie:** `SS["A"]`)

- `SS["event_id, id"]` get the selfSwitch for the event of the current map (**ie:** `SS["2, C"]`) (**do not forget the quotes**)

- `SS["map_id, event_id, id"]` get the selfSwitch for the event on a specific map (**ie:** `SS["3, 2, C"]`) (**do not forget the quotes**)

- `SS[id] = new_value` set the selfSwitch for the current event  (**ie:** `SS["A"] = true`)

- `SS["event_id, id"] = new_value` set the selfSwitch for the event of the current map (**ie:** `SS["2, C"] = false`) (**do not forget the quotes**)

-  `SS["map_id, event_id, id"] = new_value` set the selfSwitch for the event on a specific map (**ie:** `SS["3, 2, C"] = true`) (**do not forget the quotes**)

- `SV[id]` get the selfVariable for the current event  (**ie:** `SV[84]`)

- `SV["event_id, id"]` get the selfVariable for the event of the current map (**ie:** `SV["2, 19"]`) (**do not forget the quotes**)

- `SV["map_id, event_id, id"]` get the selfVariable for the event on a specific map (**ie:** `SV["3, 2, 22"]`) (**do not forget the quotes**)

- `SV[id] = new_value` set the selfVariable for the current event  (**ie:** `SV[10] = 67`)

- `SV["event_id, id"] = new_value` set the selfVariable for the event of the current map (**ie:** `SV["2, 9"] = 84`) (**do not forget the quotes**)

-  `SV["map_id, event_id, id"] = new_value` set the selfVariable for the event on a specific map (**ie:** `SV["3, 2, 38"] = 54`) (**do not forget the quotes**)

For "complexes keys", the double-quotes are mandatory because of Proxy.get !

### CODE REVIEW

**Comment by xvw** [comment]
About the "double-quotes", could you not "deal with the spread operator" ?

**Comment by grrim** [comment]
Nop. The "parameter" of `[]` is passed as a object's properties (so a String... or a Number). It is sad but I think that it is a better approach of variable handling.

**Comment by xvw** [comment]
Ok ! Why do you catch "Apply" ?

**Comment by grrim** [comment]
Nice question ;)
To preserve _backward compatibility_

**Pull request merged**
